### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by CsatiZoltan** [BenBrock/nbods#5]
Could you please tell me what the red and blue dots represent?

**Comment by benbenolson** [comment]
```
if(v >= 0.4) {
  r = 1.0; b = 0.0;
} else if(v < 0.5) {
  b = 1.0; r = 0.0;
}
cairo_set_source_rgba(context, (double)r, 0.0, (double)b, 1.0);
```
In the above sample from `nbody.cpp`, `v` is the velocity of the particle. If the velocity is greater than or equal to `0.4`, the particle is red. Otherwise, it's blue.

**Comment by CsatiZoltan** [comment]
Thanks.
